name: caller
on: [workflow_dispatch, push]
jobs:
  deploy:
    permissions:
      contents: write
      id-token: write
    uses: hmz-latest-new2/.github/.github/workflows/reusable.yml@main
    with:
      aws_role: arn:aws:iam::739275466967:role/victim-deploy-role-poc
    secrets:
      DEPLOY_SECRET: ${{ secrets.VICTIM_SECRET }}
